/** @format */

const DeckOfCards = [
  { key: '1', img: require('../img/ad.png'), value: 1 },
  { key: '2', img: require('../img/2d.png'), value: 2 },
  { key: '3', img: require('../img/3d.png'), value: 3 },
  { key: '4', img: require('../img/4d.png'), value: 4 },
  { key: '5', img: require('../img/5d.png'), value: 5 },
  { key: '6', img: require('../img/6d.png'), value: 6 },
  { key: '7', img: require('../img/7d.png'), value: 7 },
  { key: '8', img: require('../img/8d.png'), value: 8 },
  { key: '9', img: require('../img/9d.png'), value: 9 },
  { key: '10', img: require('../img/10d.png'), value: 10 },
  { key: '11', img: require('../img/jd.png'), value: 11 },
  { key: '12', img: require('../img/qd.png'), value: 12 },
  { key: '13', img: require('../img/kd.png'), value: 13 },
  { key: '14', img: require('../img/ah.png'), value: 1 },
  { key: '15', img: require('../img/2h.png'), value: 2 },
  { key: '16', img: require('../img/3h.png'), value: 3 },
  { key: '17', img: require('../img/4h.png'), value: 4 },
  { key: '18', img: require('../img/5h.png'), value: 5 },
  { key: '19', img: require('../img/6h.png'), value: 6 },
  { key: '20', img: require('../img/7h.png'), value: 7 },
  { key: '21', img: require('../img/8h.png'), value: 8 },
  { key: '22', img: require('../img/9h.png'), value: 9 },
  { key: '23', img: require('../img/10h.png'), value: 10 },
  { key: '24', img: require('../img/jh.png'), value: 11 },
  { key: '25', img: require('../img/qh.png'), value: 12 },
  { key: '26', img: require('../img/kh.png'), value: 13 },
  { key: '27', img: require('../img/ac.png'), value: 1 },
  { key: '28', img: require('../img/2c.png'), value: 2 },
  { key: '29', img: require('../img/3c.png'), value: 3 },
  { key: '30', img: require('../img/4c.png'), value: 4 },
  { key: '31', img: require('../img/5c.png'), value: 5 },
  { key: '32', img: require('../img/6c.png'), value: 6 },
  { key: '33', img: require('../img/7c.png'), value: 7 },
  { key: '34', img: require('../img/8c.png'), value: 8 },
  { key: '35', img: require('../img/9c.png'), value: 9 },
  { key: '36', img: require('../img/10c.png'), value: 10 },
  { key: '37', img: require('../img/jc.png'), value: 11 },
  { key: '38', img: require('../img/qc.png'), value: 12 },
  { key: '39', img: require('../img/kc.png'), value: 13 },
  { key: '40', img: require('../img/as.png'), value: 1 },
  { key: '41', img: require('../img/2s.png'), value: 2 },
  { key: '42', img: require('../img/3s.png'), value: 3 },
  { key: '43', img: require('../img/4s.png'), value: 4 },
  { key: '44', img: require('../img/5s.png'), value: 5 },
  { key: '45', img: require('../img/6s.png'), value: 6 },
  { key: '46', img: require('../img/7s.png'), value: 7 },
  { key: '47', img: require('../img/8s.png'), value: 8 },
  { key: '48', img: require('../img/9s.png'), value: 9 },
  { key: '49', img: require('../img/10s.png'), value: 10 },
  { key: '50', img: require('../img/js.png'), value: 11 },
  { key: '51', img: require('../img/qs.png'), value: 12 },
  { key: '52', img: require('../img/ks.png'), value: 13 },
  { key: '53', img: require('../img/back.png'), value: 0 },
];

export default DeckOfCards;

const styles = StyleSheet.create({});
